### ISSUE TITLE
refactor cpp_get_fe_gnl

### ISSUE THREAD

**Issue by pachadotdev** [pachadotdev/fixest2#31]
without this function, femlm doesn't pass `devtools::check()`

I need to fix all the lines with "TODO: ..." comments here
https://github.com/pachadotdev/fixest2/blob/cpp_get_fe_gnl/src/05_01_misc_helpers.cpp#L718
https://github.com/pachadotdev/fixest2/blob/cpp_get_fe_gnl/src/05_01_misc_helpers.cpp#L795
https://github.com/pachadotdev/fixest2/blob/cpp_get_fe_gnl/src/05_01_misc_helpers.cpp#L844

the original function is here
https://github.com/pachadotdev/fixest2/blob/master/src/misc_funs.cpp#L224

then I need to put a working function here
https://github.com/pachadotdev/fixest2/blob/cpp11_wip/src/05_01_misc_helpers.cpp

what works so far
```
devtools::install()
devtools::load_all()
feols(mpg ~ wt | cyl, data = mtcars)
```

**Comment by pachadotdev** [comment]
hi @klrmlr and @Antonov548

can you can help me with these specific lines, please?
I already translated the rest of fixest to cpp11

my goal is to create a "fixest lite" with no coefplot, latex exporting etc and just provide feols() and fepois(), and rely on the tidyverse for all visualization/tables

**Comment by krlmlr** [comment]
Thanks. Can you please add a bit more detail on what's not working and how we can help? @Antonov548: can you please take a look?

**Comment by Antonov548** [comment]
> Thanks. Can you please add a bit more detail on what's not working and how we can help? @Antonov548: can you please take a look?

Yes, sure.

**Comment by Antonov548** [comment]
@pachadotdev 
I think you can just update function interface. 

`list cpp_get_fe_gnl(int Q, int N, writable::doubles sumFE, writable::integers_matrix<> dumMat, writable::integers cluster_sizes, writable::integers_matrix obsCluster)`

As I can see this function is used from R with matrix argument. Matrix under the hood is also just a Vector. So I think it's just better to explicitly use `integers_matrix` there. 
Rcpp inside `operator(int, int)` convert Vector to Matrix and if it's not Matrix, it throws exception. 

After changing type of `obsCluster` to `integers_matrix` you can just use same operator as it was in Rcpp.

Let me know please, if it's helpful.

**Comment by pachadotdev** [comment]
@Antonov548 I read you comment carefully, and I was able to fix 2/3 of the issue

now I only need to push back a value to the list https://github.com/pachadotdev/fixest2/commit/6a301bbf8a559b0fcf2fbb2489d713e2af8ba86e

the pkg can be installed and OLS is working ok, but this issue makes GLM fail

**Comment by Antonov548** [comment]
@pachadotdev Do you have reference with Rcpp? Not sure what should be done. `nb_ref` is array. And it could be pushed to as element of `res`. Would you like to add array to the end of `res` list? As I see `res` contains `double`'s. Doesn't it make sense to use `cpp11::doubles`?

https://github.com/pachadotdev/fixest2/blob/6a301bbf8a559b0fcf2fbb2489d713e2af8ba86e/src/05_01_misc_helpers.cpp#L843-L847

**Comment by pachadotdev** [comment]
> 



> @pachadotdev Do you have reference with Rcpp? Not sure what should be done. `nb_ref` is array. And it could be pushed to as element of `res`. Would you like to add array to the end of `res` list? As I see `res` contains `double`'s. Doesn't it make sense to use `cpp11::doubles`?
> 
> https://github.com/pachadotdev/fixest2/blob/6a301bbf8a559b0fcf2fbb2489d713e2af8ba86e/src/05_01_misc_helpers.cpp#L843-L847

thanks!
yes, it also makes sense to use doubles
I wanted to add a final 'coordinate' at the end of  the list `res`

**Comment by Antonov548** [comment]
> > 
> 
> > @pachadotdev Do you have reference with Rcpp? Not sure what should be done. `nb_ref` is array. And it could be pushed to as element of `res`. Would you like to add array to the end of `res` list? As I see `res` contains `double`'s. Doesn't it make sense to use `cpp11::doubles`?
> > https://github.com/pachadotdev/fixest2/blob/6a301bbf8a559b0fcf2fbb2489d713e2af8ba86e/src/05_01_misc_helpers.cpp#L843-L847
> 
> thanks! yes, it also makes sense to use doubles I wanted to add a final 'coordinate' at the end of the list `res`
> 
> with doubles it doesn't like it either

Sorry, I misunderstood. It should return `list` entity.

You can change this line: https://github.com/pachadotdev/fixest2/blob/6a301bbf8a559b0fcf2fbb2489d713e2af8ba86e/src/05_01_misc_helpers.cpp#L562

to `std::vector<int> nb_ref(Q);`

And then this line:
https://github.com/pachadotdev/fixest2/blob/6a301bbf8a559b0fcf2fbb2489d713e2af8ba86e/src/05_01_misc_helpers.cpp#L843

to `res[Q] = as_sexp(nb_ref);`

Let me know please if it makes sense.

**Comment by pachadotdev** [comment]
thanks @Antonov548 !!
this works, I am still trying to understand why
