### ISSUE TITLE
error with cpp_partialDerivative_other()

### ISSUE THREAD

**Issue by pachadotdev** [pachadotdev/fixest2#36]
# cpp11

in https://github.com/pachadotdev/fixest2/tree/cpp11_wip, there's an error that return the next message

error message (crashes the R session)

```
ℹ Loading fixest2[14107:14107:20230205,095116.104160:ERROR process_memory_range.cc:86] read out of range
[14107:14107:20230205,095116.104194:ERROR elf_image_reader.cc:558] missing nul-terminator
[14107:14107:20230205,095116.104254:ERROR elf_dynamic_array_reader.h:61] tag not found
[14107:14107:20230205,095116.105571:ERROR elf_dynamic_array_reader.h:61] tag not found
```

the steps to obtain the error from bash/shell are

```
git clone --depth 1 https://github.com/pachadotdev/fixest2.git
cd fixest2
git checkout cpp11_wip
R
```

and then in R

```
if (!require(devtools)) install.packages("devtools")
devtools::check()
```

I was able to trace down the issue and is https://github.com/pachadotdev/fixest2/blob/cpp11_wip/R/femlm.R#L1011, where the problem is integer vs double, which breaks the negbin example in https://github.com/pachadotdev/fixest2/blob/cpp11_wip/vignettes/fixest_walkthrough.Rmd#L153-L154

I tried to convert the input matrix to integer in R before passing it to the C++ function. If I don't do that then it says "expected integer, actual double"

# Rcpp

in branch https://github.com/pachadotdev/fixest2/tree/master, the same example works

**Comment by pachadotdev** [comment]
hi @Antonov548!
maybe you've found something similar to this error, any ideas?

**Comment by Antonov548** [comment]
> hi @Antonov548! maybe you've found something similar to this error, any ideas?

Hi.
I haven't faced it yet. But I will try to reproduce this issue.

**Comment by pachadotdev** [comment]
> 

thanks! I replied in your RPostgres PR regarding CRAN links
